#!/bin/bash

set -x

if [[ ! $1 ]] ; then 
  echo "No version \$1 (e.g. 3.0.0)"
  exit 1
fi

version=$1


# --------------------------------------------------------------------
# Make the archive docs    
# --------------------------------------------------------------------
cd docs

make html $version

cd $version

rm -fr _downloads/*
cp -pv ../source/sample_files/cf_tutorial_files.zip _downloads
cp -pv ../source/tutorial.py _downloads

for download_file in cf_tutorial_files.zip tutorial.py
do		     
  sed -i "s/\(href=._downloads\).*\($download_file\)/\1\/\2/" tutorial.html 
done

# --------------------------------------------------------------------
# Add and commit the archive
# --------------------------------------------------------------------
git add \
    *.html \
    classes/*.html \
    function/*.html \
    method/*.html \
    attribute/*.html \
    *.inv \
    *.js \
    _sources \
    _static \
    _downloads/*

git commit -a -m "v$version archive documentation"

set +x
