#!/bin/bash

set -x

if [[ ! $1 ]] ; then 
  echo "No version \$1 (e.g. 3.0.0)"
  exit 1
fi

version=$1

# --------------------------------------------------------------------
# Make the latest docs    
# --------------------------------------------------------------------
cd docs
rm -fr .doctrees
make html .

#mv _downloads/*/*.nc _downloads

cp source/sample_files/cf_tutorial_files.zip _downloads
cp source/tutorial.py _downloads

# --------------------------------------------------------------------
# Add and commit the latest
# --------------------------------------------------------------------
git add \
    *.html \
    classes/*.html \
    function/*.html \
    method/*.html \
    attribute/*.html \
    *.inv \
    *.js \
    _sources \
    _static \
    _downloads/cf_tutorial_files.zip \
    _downloads/tutorial.py

git commit -a -m "v$version latest documentation"

set +x
