#!/bin/bash

set -x

rm_doctrees=true
if [[ $1 ]] ; then 
  rm_doctrees=$1
fi

dir=beta

# Make zip file
cd docs/source/sample_files
zip cf_tutorial_files.zip *.nc *.pp
cd -

# --------------------------------------------------------------------
# Make the latest docs    
# --------------------------------------------------------------------
cd docs
if [[ $rm_doctrees = "true" ]] ; then
   rm -fr $dir/.doctrees
fi
make html $dir

cp -pv source/sample_files/cf_tutorial_files.zip source/tutorial.py $dir/_downloads

cd $dir

for download_file in cf_tutorial_files.zip tutorial.py
do		     
  sed -i "s#\(href=._downloads\).*\($download_file\)#\1\/\2#" tutorial.html 
done

# --------------------------------------------------------------------
# Add and commit the latest beta docs
# --------------------------------------------------------------------
git add \
    *.html \
    classes/*.html \
    function/*.html \
    method/*.html \
    attribute/*.html \
    *.inv \
    *.js \
    _sources \
    _static \
    _downloads/cf_tutorial_files.zip \
    _downloads/tutorial.py

git commit -a -m "latest beta documentation"

set +x
