#!/bin/bash

# --------------------------------------------------------------------
# Install and run tests in ~/tmp
# --------------------------------------------------------------------

set -x

if [[ ! $1 ]] ; then 
  echo "Must set version as \$1 (e.g. 3.10.0)"
  exit 1
fi

vn=$1

dir=~/tmp/test_cf-python
rm -fr $dir

tar ztvf dist/cf_python-$vn.tar.gz

pip install dist/cf_python-$vn.tar.gz -t $dir --no-deps

export PYTHONPATH=$dir:$PYTHONPATH
export PATH=$dir/bin:$PATH

cd $dir/cf/test
ls -o

./individual_tests.sh
test_result_status=$?

set -x

exit $test_result_status
