#!/bin/bash

# --------------------------------------------------------------------
# Install and run tests in ~/tmp
# --------------------------------------------------------------------

set -x

if [[ ! $1 ]] ; then 
  echo "Must set version as \$1 (e.g. 3.2.0)"
  exit 1
fi

vn=$1

mkdir -p ~/tmp
cp dist/cf-python-$vn.tar.gz ~/tmp
cd ~/tmp
rm -fr ~/tmp/test ~/tmp/bin ~/tmp/lib ~/tmp/cf-python-$vn
tar zxvf cf-python-$vn.tar.gz
cd cf-python-$vn
python setup.py install --home=~/tmp

export PYTHONPATH=~/tmp/lib/python:$PYTHONPATH
export PATH=~/tmp/bin:$PATH

cd ~/tmp/lib/python/cf/test
python run_tests.py

#mpirun -n 3 python run_tests.py
#mpirun -n 2 python run_tests.py
#mpirun -n 1 python run_tests.py

set -x

