#!/bin/bash

# --------------------------------------------------------------------
# Run this within a local respository directory to upload the latest
# release to PyPi
#
# It is presumed that `python setup.py sdist` has already been run.
#
#>> ./upload_to_pypi 3.0.2
# --------------------------------------------------------------------

set -x

if [[ ! $1 ]] ; then
  echo "No version \$1 (e.g. 3.0.2)"
  exit 1
fi

version=$1

tarball=dist/cf-python-${version}.tar.gz

if [[ ! -f $tarball ]] ; then
  echo "Tar ball for version $version does not exist: $tarball"
  exit 2
fi

which twine

twine upload $tarball

set +x
