#!/bin/bash

set -x

sample_files=sample_files
test_tutorial=test_tutorial

if [[ -d "$test_tutorial" ]] ; then
  rm $test_tutorial/*
else
  mkdir $test_tutorial
fi

cp $sample_files/* $test_tutorial

cd $test_tutorial

zip cf_tutorial_files.zip *.nc *.pp

set +x
